version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: injective
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  injective-service:
    image: 
      ghcr.io/akash-network/cosmos-omnibus:v0.3.42-injective-v1.11.6-1688984159
    cpu: 8.0
    memory: 64Gi
    storage:
      size: 7Gi
    variables:
      MONIKER: my-moniker-1
      CHAIN_JSON: 
        https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/chain.json
      P2P_POLKACHU: '1'
      SNAPSHOT_DATA_PATH: data
      SNAPSHOT_WASM_PATH: wasm
      SNAPSHOT_URL: https://tools.highstakes.ch/files/injective.tar.gz
      MINIMUM_GAS_PRICES: 500000000inj
      INJECTIVED_IAVL_DISABLE_FASTNODE: 'true'
      INJECTIVED_API_ENABLE: 'true'
    network:
      ingress:
        port: 9090
        public: true
