version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: ray
providers:
  akash:
    status: prefer
services:
  ray-head:
    image: rayproject/ray:nightly-py310-gpu
    cpu: 5.0
    memory: 10Gi
    storage:
      size: 10Gb
    variables:
      RAY_ADDRESS: ray-head:6380
    network:
      ingress:
        port: 8265
        public: true
  ray-worker:
    image: rayproject/ray:nightly-py310-gpu
    cpu: 5.0
    memory: 10Gi
    storage:
      size: 10Gb
    network:
      ingress:
        port: 8078
        public: true
