version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: drupal
providers:
  akash:
    status: prefer
services:
  drupal:
    image: drupal
    cpu: 1.0
    memory: 1Gi
    storage:
      size: 1Gi
    network:
      ingress:
        port: 80
        public: true
