version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: supermario
providers:
  akash:
    status: prefer
services:
  supermario:
    image: pengbai/docker-supermario
    cpu: 1.0
    memory: 512Mi
    storage:
      size: 512Mi
    network:
      ingress:
        port: 8080
        public: true
