version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: ollama-cpu
providers:
  akash:
    status: prefer
services:
  ollama:
    image: ollama/ollama:0.13.4
    cpu: 24.0
    memory: 28Gi
    storage:
      size: 100Gi
    variables:
      MODEL: phi3
    network:
      ingress:
        port: 11434
        public: true
