version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: whoogle-search
providers:
  akash:
    status: prefer
services:
  whoogle:
    image: benbusby/whoogle-search:latest
    cpu: 1.0
    memory: 1Gi
    storage:
      size: 1Gi
    variables:
      WHOOGLE_USER: user
      WHOOGLE_PASS: password
    network:
      ingress:
        port: 5000
        public: true
