version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: AI-Image-App
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  gpu-app:
    image: overshard/ai-art
    cpu: 1.0
    memory: 38Gi
    storage:
      size: 100Gi
    network:
      ingress:
        port: 3000
        public: true
