version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: ufo-data-vis
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  ufoweb:
    image: wlouie1/ufo-data-vis:latest
    cpu: 1.0
    memory: 512Mi
    storage:
      size: 512Mi
    network:
      ingress:
        port: 80
        public: true
