version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: pancake-swap
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  pancakeswap:
    image: yuravorobei/pancake-swap
    cpu: 1.0
    memory: 512Mi
    storage:
      size: 1Gi
    network:
      ingress:
        port: 8080
        public: true
