version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: tensorflow-webapp-mnist
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  tfserver:
    image: wlouie1/mnist-tf-serve:1.0
    cpu: 0.2
    memory: 512Mi
    storage:
      size: 512Mi
    network:
      ingress:
        port: 8501
        public: false
  flaskserver:
    image: wlouie1/mnist-flask-serve:1.0
    cpu: 0.2
    memory: 256Mi
    storage:
      size: 1Gi
    network:
      ingress:
        port: 5000
        public: false
  web:
    image: wlouie1/mnist-app:1.0
    cpu: 0.1
    memory: 256Mi
    storage:
      size: 512Mi
    network:
      ingress:
        port: 80
        public: true
