version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: serverbench
providers:
  akash:
    status: prefer
services:
  serverbench:
    image: cryptoandcoffee/akash-serverbench:9
    cpu: 4.0
    memory: 2Gi
    storage:
      size: 4Gi
    network:
      ingress:
        port: 80
        public: true
