version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: speedtest-cli
providers:
  akash:
    status: prefer
services:
  speedtest-cli:
    image: cryptoandcoffee/akash-speedtest-cli
    cpu: 1.0
    memory: 512Mi
    storage:
      size: 512Mi
    network:
      ingress:
        port: 80
        public: true
