version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: confluence
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  confluence:
    image: atlassian/confluence-server:latest
    cpu: 0.1
    memory: 512Mi
    storage:
      size: 2Gi
    network:
      ingress:
        port: 8090
        public: true
