version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: t-rex-c11
providers:
  akash:
    status: prefer
services:
  t-rex-c11:
    image: cryptoandcoffee/akash-gpu-miner-t-rex-c11:21
    cpu: 0.5
    memory: 768Mi
    storage:
      size: 512Mi
    variables:
      ALGO: '"etchash"'
      WALLET_ADDRESS: '""'
      POOL: '"stratum+ssl://us-solo-etc.2miners.com:15050"'
      PASSWORD: '"x"'
      OPTIONS: '"--api-bind-http 0.0.0.0:4061 --api-read-only --no-nvml"'
    network:
      ingress:
        port: 4061
        public: true
