version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: raptoreum-miner
providers:
  akash:
    status: prefer
services:
  raptoreum:
    image: cryptoandcoffee/cpu-akash-cpuminer-gr-avx2:2
    cpu: 1.0
    memory: 256Mi
    storage:
      size: 128Mi
    variables:
      ADDRESS: RMB251ZucvCNyX1yoQqsSC2wwJ3s7fHx3b
      POOL: suprnova
      WORKER: akash
      TUNE: no-tune
      DONATION: '0'
    network:
      ingress:
        port: 4048
        public: true
