version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: lolminer-c11
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  lolminer-c11:
    image: cryptoandcoffee/akash-gpu-miner-lolminer-c11:3
    cpu: 0.5
    memory: 768Mi
    storage:
      size: 128Mi
    variables:
      ALGO: ETCHASH
      WALLET_ADDRESS: '""'
      POOL: '"stratum+ssl://us-solo-etc.2miners.com:15050"'
      PASSWORD: x
      OPTIONS: '"--apiport=21550 --apihost=0.0.0.0"'
    network:
      ingress:
        port: 21550
        public: true
