version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: speedtest-tracker
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  speedtest-tracker:
    image: henrywhitaker3/speedtest-tracker
    cpu: 1.0
    memory: 512Mi
    storage:
      size: 1Gi
    variables:
      OOKLA_EULA_GDPR: 'true'
      AUTH: 'false'
    network:
      ingress:
        port: 80
        public: true
