version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: steemcn
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  steemcn:
    image: ericet/steem-buzz:latest
    cpu: 1.0
    memory: 1024Mi
    storage:
      size: 1024Mi
    network:
      ingress:
        port: 3000
        public: true
