version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: grafana
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  grafana:
    image: grafana/grafana
    cpu: 1.0
    memory: 1Gi
    storage:
      size: 512Mi
    network:
      ingress:
        port: 3000
        public: true
