version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: radicle
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  node:
    image: 
      quay.io/vpavlin0/radicle-seed@sha256:d5070f85cd965bfbb4f9b22415b6ed19d9922c5afaa3e8a3320f5c32e2714b7e
    cpu: 1.0
    memory: 1Gi
    storage:
      size: 1Gi
    variables:
      RAD_ALIAS: ''
      RAD_SEEDS: rad:zNd4qti1Jc69mCBQAdBeK3Avzy4R
      RAD_PINNED_REPOS: rad:zNd4qti1Jc69mCBQAdBeK3Avzy4R
      RAD_EXTERNAL_ADDR: ''
      RAD_SEEDING_POLICY: block
      RAD_HTTP_ENABLE: 'true'
    network:
      ingress:
        port: 8776
        public: true
