version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: traffmonetizer
providers:
  akash:
    status: prefer
services:
  traffmonetizer:
    image: traffmonetizer/cli_v2:latest
    cpu: 0.1
    memory: 96Mi
    storage:
      size: 6Mi
    network:
      ingress:
        port: 80
        public: true
