version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: moneroocean
providers:
  akash:
    status: prefer
services:
  miner-moneroocean:
    image: cryptoandcoffee/akash-moneroocean:112
    cpu: 1.0
    memory: 1Gi
    storage:
      size: 16Mi
    variables:
      WALLET: ''
      MEMORY_SIZE: 1Gi
      WORKER: akash
      MODE: light
    network:
      ingress:
        port: 80
        public: true
