version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: onetimepad
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  onetimepad:
    image: jenkinsplc/onetimepad
    cpu: 1.0
    memory: 512Mi
    storage:
      size: 512mi
    network:
      ingress:
        port: 3000
        public: true
