version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: quill-editor
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  quill:
    image: akashquill/quill:v1
    cpu: 1.0
    memory: 512Mi
    storage:
      size: 1512Mi
    network:
      ingress:
        port: 8501
        public: true
