version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: FLock-training-node
providers:
  akash:
    status: prefer
services:
  flock-train:
    image: public.ecr.aws/e7z6j8c3/flock:training-quickstart-akash
    cpu: 8.0
    memory: 24Gi
    storage:
      size: 100Gi
    variables:
      HF_USERNAME: ''
      TASK_ID: ''
    secrets:
    - secret_ref: flock_api_key
      mode: env
      keys:
        value: FLOCK_API_KEY
    - secret_ref: hf_token
      mode: env
      keys:
        value: HF_TOKEN
    network:
      ingress:
        port: 3000
        public: true
