version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: Ethereum_2.0
providers:
  akash:
    status: prefer
services:
  ethereum:
    image: dimokus88/ubuntu:1.3
    cpu: 4.0
    memory: 9Gi
    storage:
      size: 600Gi
    variables:
      DEPOSIT_JSON_BASE64: ''
      DEPOSIT_FILE_NAME: ''
      KEYSTORE_JSON_BASE64: ''
      KEYSTORE_FILE_NAME: ''
      ACCOUNT_ETH_PASS: ''
      RECEPIENT: ''
      NETWORK: ''
      SSH_PASS: ''
      LIGHTHOUSE_LINK: 
        https://github.com/sigp/lighthouse/releases/download/v3.5.1/lighthouse-v3.5.1-x86_64-unknown-linux-gnu-portable.tar.gz
      SNAP_URL: https://prater-checkpoint-sync.stakely.io
    network:
      ingress:
        port: 22
        public: true
