version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: nbminer-c11
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  nbminer-c11:
    image: cryptoandcoffee/akash-gpu-miner-nbminer-c11:2
    cpu: 0.25
    memory: 512Mi
    storage:
      size: 128Mi
    variables:
      ALGO: '"etchash"'
      WALLET_ADDRESS: '""'
      POOL: '"stratum+ssl://us-solo-etc.2miners.com:15050"'
      PASSWORD: '"x"'
      OPTIONS: '""'
    network:
      ingress:
        port: 4061
        public: true
