version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: ghrunner
providers:
  akash:
    status: prefer
services:
  ghrunner:
    image: ghcr.io/myoung34/docker-github-actions-runner:2.330.0-ubuntu-noble
    cpu: 1.0
    memory: 2gb
    storage:
      size: 10gb
    variables:
      REPO_URL: https://github.com/<org>/<repo>
      RUNNER_NAME: ghrunner
    secrets:
    - secret_ref: runner_token
      mode: env
      keys:
        value: RUNNER_TOKEN
    network:
      ingress:
        port: 80
        public: true
