version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: CockroachDB
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  cockroachdb:
    image: cockroachdb/cockroach:latest
    cpu: 1.0
    memory: 1Gi
    storage:
      size: 1Gi
    network:
      ingress:
        port: 26257
        public: true
