version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: babyagi
providers:
  akash:
    status: prefer
services:
  babyagi:
    image: cryptoandcoffee/akash-babyagi:2
    cpu: 8.0
    memory: 4.75Gi
    storage:
      size: 16Gi
    variables:
      LLM_MODEL: gpt-3.5-turbo
      LLAMA_MODEL_PATH: ''
      OPENAI_TEMPERATURE: '0.5'
      RESULTS_STORE_NAME: baby-agi-test-table
      INSTANCE_NAME: BabyAGI
      COOPERATIVE_MODE: none
      OBJECTIVE: Solve world hunger
      INITIAL_TASK: Develop a task list
      DOTENV_EXTENSIONS: ''
      ENABLE_COMMAND_LINE_ARGS: 'false'
    secrets:
    - secret_ref: openai_api_key
      mode: env
      keys:
        value: OPENAI_API_KEY
    network:
      ingress:
        port: 3000
        public: true
