version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: yacy
providers:
  akash:
    status: prefer
services:
  yacy:
    image: yacy/yacy_search_server:latest
    cpu: 0.1
    memory: 256Mi
    network:
      ingress:
        port: 8090
        public: true
