version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: budibase
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  budibase:
    image: budibase/budibase:v2.0.31
    cpu: 1.0
    memory: 2Gi
    storage:
      size: 2Gi
    network:
      ingress:
        port: 80
        public: true
