version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: folding-at-home
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  folding-at-home:
    image: yurinnick/folding-at-home:latest
    cpu: 1.0
    memory: 1Gi
    storage:
      size: 1Gi
    variables:
      TEAM: '0'
      ENABLE_GPU: 'false'
      ENABLE_SMP: 'true'
    network:
      ingress:
        port: 7396
        public: true
