version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: steamcmd
providers:
  akash:
    status: prefer
services:
  steamcmd:
    image: cm2network/steamcmd
    cpu: 1.0
    memory: 1Gi
    storage:
      size: 1Gi
    network:
      ingress:
        port:
        public: true
