version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: privategpt-gpu
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  privategpt:
    image: 3x3cut0r/privategpt:latest
    cpu: 4.0
    memory: 16Gi
    storage:
      size: 100Gi
    network:
      ingress:
        port: 8080
        public: true
