version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: Llama-3.1-405B-AWQ-INT4
providers:
  akash:
    status: prefer
services:
  vllm:
    image: 
      vllm/vllm-openai:v0.6.2@sha256:730ef3d3c17a217b34cfdbfd99be80b3f459e37ef2fc0c5c43ba70752dad08ae
    cpu: 16.0
    memory: 128Gi
    storage:
      size: 100Gi
    secrets:
    - secret_ref: hf_token
      mode: env
      keys:
        value: HF_TOKEN
    network:
      ingress:
        port: 8000
        public: true
