version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: Kadena
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  node:
    image: ghcr.io/kadena-io/chainweb-node/ubuntu:2.18
    cpu: 2.0
    memory: 4Gi
    storage:
      size: 1Gi
    network:
      ingress:
        port: 443
        public: true
