version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: kawpow-pool-ravencoin
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  kawpow-pool:
    image: cryptoandcoffee/akash-kawpow-pool:9
    cpu: 2.0
    memory: 4Gi
    storage:
      size: 8Gi
    variables:
      RAVEN_ENABLE: 'true'
      NEOXA_ENABLE: 'false'
      MEOWCOIN_ENABLE: 'false'
      WALLET: ''
      FEE_WALLET: ''
      FEE_AMOUNT: '0.1'
      DAEMON_HOST: ravencoin
      DAEMON_PORT: '8766'
      DAEMON_USER: user1
      DAEMON_PASS: pass1
    network:
      ingress:
        port: 8767
        public: true
  ravencoin:
    image: cryptoandcoffee/akash-ravencoin:2
    cpu: 2.0
    memory: 4Gi
    storage:
      size: 64Gi
    secrets:
    - secret_ref: private_key
      mode: env
      keys:
        value: PRIVATE_KEY
    network:
      ingress:
        port: 8766
        public: false
