version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: SurrealDB
providers:
  akash:
    status: prefer
services:
  surrealdb:
    image: surrealdb/surrealdb:1.0.0-beta.8
    cpu: 1.0
    memory: 1Gi
    storage:
      size: 1Gi
    network:
      ingress:
        port: 8000
        public: true
