version: v0.2
organization_id: '{{ORG_ID}}'
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'

cluster:
  name: tetris2-gcp

providers:
  dcf:
    status: prefer
  akash:
    status: fallback
    max_price: 15.00
  gcp:
    status: prefer
    network_tier: Standard
    ip_version: IPV4

regions:
  mode: explicit
  explicit:
    - region_id: gcp-europe-west1
      provider: gcp
      is_primary: true
      network_tier: Standard
      ip_version: IPV4

services:
  tetris:
    image: uzyexe/tetris
    cpu: 0.25
    memory: 256Mi
    storage:
      size: 512Mi
    mesh:
      enabled: false
    network:
      ingress:
        port: 80
        public: true
