version: v0.2
project_id: '{{PROJECT_ID}}'
cluster_id: '{{CLUSTER_ID}}'
cluster:
  name: XLM-RoBERTa
providers:
  dcf:
    status: prefer
  akash:
    status: fallback
services:
  roberta:
    image: clydedevv/xlm-roberta-app:0.0.9
    cpu: 4.0
    memory: 4Gi
    storage:
      size: 10Gi
    network:
      ingress:
        port: 80
        public: true
